version: "3"

services:
  mibreit-web-dev:
    image: mibreit/mibreit-web-dev:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - /home/develop/node_modules
      - ..:/home/develop
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  mibreit-web-test:
    image: php:apache
    volumes:
      - ../dist:/var/www/html
    ports:
      - "8080:80"
  