version: "3"

services:
  mibreit-web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/developer/develop/node_modules
      - ..:/home/developer/develop
      - ${HOME}/.ssh:/home/developer/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - USER=developer
      - UID
  mibreit-web-dev-test:
    image: webdevops/php-apache:8.2-alpine
    volumes:
      - ../dist:/app
    ports:
      - "80:80"
  mibreit-web-dev-db-blog:
    image: mariadb:latest
    volumes:
      - ../_data/db-blog:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test 
      MYSQL_PASSWORD: password
  mibreit-web-dev-phpmyadmin-blog:
    depends_on:
      - mibreit-web-dev-db-blog
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mibreit-web-dev-db-blog
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 100M
